<?xml version="1.0" encoding="utf-8"?><Database Name="webapidb" Class="KoreDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PRASHANT\SQLEXPRESS;Initial Catalog=webapidb;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="webapidbConnectionString" Provider="System.Data.SqlClient" />
</Database>